spring:
  datasource:
    url: jdbc:mysql://192.168.85.90:3306/user_db_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # sharding-jdbc 水平分库分表策略
  # 配置数据源，给数据源起别名
  # 水平分库需要配置多个数据库
  sharding-sphere:
    datasource:
      names: master1,slave1,slave2
      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.85.90:3306/user_db_1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
        username: root
        password: root
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.85.91:3307/user_db_1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
        username: root
        password: root
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.85.90:3308/user_db_1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
        username: root
        password: root
    # 打开 sql 输出日志
    props:
      sql.show: true
    master-slave:
      load-balance-algorithm-type: round_robin
    sharding:
      master-slave-rules:
        master:
          master-data-source-name: master1
          slave-data-source-names: slave1,slave2
server:
  port: 8003